Adding new frontend
gosqasorg/asset-provenance-tracking pull request #54
Opened 2023-11-17 04:31 UTC by K42IE

Adding the new Nuxt repo to the existing codebase.

2023-11-17 15:16 UTC, RobertLRead approved these changes
I've cast my eyes over this and it looks good to the extent that I understand it. I need to more fully understand how we are keeping the front end separate from the backend.

2023-11-17 17:21 UTC, devhawk commented on public/ThumbsRating.js
> +import html from './html.js';
Why is this file JS instead of TS?

2023-11-17 17:22 UTC, devhawk commented on public/ThumbsRating.js
> +
Also, should this file be in the `/packages/frontend/public` folder instead of the `/public` folder?

2023-11-17 17:24 UTC, devhawk requested changes
requested changes in code comments

2023-11-20 23:11 UTC, devhawk commented on public/ThumbsRating.js
> +import html from './html.js';
Maybe a better question is why isn't this a component?

2023-11-21 03:06 UTC, devhawk approved these changes

2023-11-21 03:10 UTC, merged